[project]
name = "dasshh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.0",
    "litellm>=1.69.3",
    "numpydoc>=1.8.0",
    "sqlalchemy>=2.0.41",
    "textual>=3.2.0",
]
